// Use these to configure automatic import sorting & grouping
const exportSortRules = [
    // Packages. `vue` related packages come first.
    // Things that start with a letter (or digit or underscore), or `@` followed by a letter.
    ['^vue', '^@?\\w'],
    // For custom namespaced packages, add more groups here if needed
    [
        /* e.g.

            '^@my-project/components\\w',
            '^@my-project/utils\\w',

            etc.
        */
    ]
]

module.exports = {
    env: {
        browser: true,
        es2021: true,
        // Fixes no-undef warnings generated by compiler macros such as defineProps and defineEmits
        'vue/setup-compiler-macros': true
    },
    extends: [
        'airbnb-base',
        'eslint:recommended',
        'plugin:vue/vue3-recommended',
        // 'plugin:vue/recommended', <-- Use this if you are using Vue.js 2.x
        'prettier'
    ],
    parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module'
    },
    plugins: ['vue', 'simple-import-sort', 'prettier'],
    rules: {
        // Start Filip
        // indent: ['error', 4],
        'linebreak-style': ['error', 'unix'],
        quotes: ['error', 'single'],
        semi: ['error', 'never'],
        'vue/html-closing-bracket-newline': [
            'error',
            {
                singleline: 'never',
                multiline: 'always'
            }
        ],
        'vue/html-closing-bracket-spacing': [
            'error',
            {
                startTag: 'never',
                endTag: 'never',
                selfClosingTag: 'always'
            }
        ],
        'vue/max-attributes-per-line': [
            'error',
            {
                singleline: 2,
                multiline: 1
            }
        ],
        'vue/first-attribute-linebreak': [
            'error',
            {
                singleline: 'ignore',
                multiline: 'below'
            }
        ],
        // End Filip
        'import/no-extraneous-dependencies': [
            'error',
            {
                peerDependencies: true
            }
        ],
        'import/first': 'error',
        'import/newline-after-import': 'error',
        'import/no-duplicates': 'error',
        'sort-imports': 'off',
        'no-empty-function': [
            'error',
            {
                allow: ['constructors']
            }
        ],
        'no-const-assign': 'warn',
        'no-this-before-super': 'warn',
        'no-undef': 'error',
        'no-unreachable': 'warn',
        'no-underscore-dangle': [
            'error',
            {
                allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__', '_allPostsMeta']
            }
        ],
        'no-unused-vars': [
            'error',
            {
                vars: 'local',
                args: 'none',
                ignoreRestSiblings: true,
                varsIgnorePattern: '^_'
            }
        ],
        'no-multiple-empty-lines': [
            'error',
            {
                max: 1
            }
        ],
        'constructor-super': 'warn',
        'valid-typeof': 'warn',
        'comma-spacing': 'warn',
        'computed-property-spacing': 'warn',
        'class-methods-use-this': 'off',
        'max-len': [
            'error',
            {
                code: 120,
                ignoreUrls: true,
                ignoreStrings: true,
                ignoreTemplateLiterals: true,
                ignoreRegExpLiterals: true
            }
        ],
        'quote-props': [1, 'as-needed'],
        'no-param-reassign': [
            'error',
            {
                props: false
            }
        ],
        'no-trailing-spaces': [
            'warn',
            {
                skipBlankLines: true
            }
        ],
        'no-use-before-define': ['off'],
        'padding-line-between-statements': [
            'error',
            {
                blankLine: 'always',
                prev: '*',
                next: 'return'
            },
            {
                blankLine: 'always',
                prev: [
                    'multiline-const',
                    'multiline-let',
                    'multiline-var',
                    'multiline-expression',
                    'multiline-block-like'
                ],
                next: '*'
            },
            {
                blankLine: 'always',
                prev: ['const', 'let', 'var', 'expression', 'multiline-block-like'],
                next: ['export']
            },
            {
                blankLine: 'always',
                prev: 'directive',
                next: '*'
            },
            {
                blankLine: 'any',
                prev: 'directive',
                next: 'directive'
            },
            {
                blankLine: 'always',
                prev: 'block-like',
                next: '*'
            },
            {
                blankLine: 'always',
                prev: 'expression',
                next: '*'
            },
            {
                blankLine: 'always',
                prev: ['case', 'default'],
                next: '*'
            }
        ],
        'prefer-destructuring': [
            'error',
            {
                object: true,
                array: false
            }
        ],
        'prefer-const': ['error'],
        'prefer-rest-params': ['error'],
        'prefer-spread': ['off'],
        'prettier/prettier': [
            'warn',
            {
                printWidth: 120,
                singleQuote: true,
                tabWidth: 4,
                semi: false,
                trailingComma: 'none',
                bracketSpacing: true,
                arrowParens: 'avoid'
            }
        ],
        'func-names': [
            'error',
            'always',
            {
                generators: 'as-needed'
            }
        ],
        'import/prefer-default-export': 'off',
        'spaced-comment': 'error',
        'simple-import-sort/imports': [
            'error',
            {
                groups: exportSortRules
            }
        ]
    }
}
